### ISSUE TITLE
Cholmod error 'X and/or Y have wrong dimensions'

### ISSUE THREAD

**Issue by kauedesousa** [hturner/PlackettLuce#24]
Happen when applying pltree in bagging using many attributes (> 62)

**Comment by kauedesousa** [comment]
Amplify the minsize in pltree() avoid this problem.

**Comment by hturner** [comment]
Glad this solved the problem for you, but I will keep this open to check if there is an issue with selecting zero or only one element of a grouped_rankings object (or if there is an issue with partykit that needs reporting).

**Comment by hturner** [comment]
Selecting zero or one element of a grouped_rankings objects seems to work fine and I can't reproduce the error, so closing this now.
