### ISSUE TITLE
could not find function "isFALSE"

### ISSUE THREAD

**Issue by kauedesousa** [hturner/PlackettLuce#35]
Dear Heather, I am using the v0.2-5 but I am getting this error:

`Error in isFALSE(gamma) : could not find function "isFALSE"`

Here an example:

library("PlackettLuce")
example("beans", package = "PlackettLuce")
G <- grouped_rankings(R, rep(seq_len(nrow(beans)), 4))
d <- cbind(G, beans)
mod <- pltree(G ~ maxTN, data = d)

**Comment by hturner** [comment]
Ah, it seems `isFALSE` was added in R 3.5 and I guess you are using an older version.

I need to resubmit to CRAN shortly as there is a separate issue on some platforms, so I shall try to remove this dependency then.

Meanwhile, does it work if you define it directly in the R session, i.e.

     isFALSE <- function(x) is.logical(x) && length(x) == 1L && !is.na(x) && !x

?

**Comment by kauedesousa** [comment]
I was using R 3.4, but decided to go with R 3.5. And it works just fine.
