### ISSUE TITLE
update the beans data

### ISSUE THREAD

**Issue by kauedesousa** [hturner/PlackettLuce#41]
Dear Heather, 

I want to use the beans data as a demo for the paper that I am writing for the package [climatrends](https://agrobioinfoservices.github.io/climatrends/index.html). But the current version of PlackettLuce::beans is missing the planting_dates and geographic coordinates. 

What do you think in updating this dataset? I can do it and make a pull request.

**Comment by hturner** [comment]
Sorry for slow response. I thought initially this might break the `pltree()` examples where I have used `G ~ . `, but it seems I have already restricted the data there.

So this would be fine and I would welcome a pull request.

**Comment by hturner** [comment]
Merged into master so will be in next CRAN release.
